export interface InstagramPost {
  id: string;
  url: string;
}

export const instagramPosts: InstagramPost[] = [
{ id: "1", url: "https://www.instagram.com/p/DdwYK14GWb_/" },  
{ id: "2", url: "https://www.instagram.com/p/DRb5Uhoj7I2" },
{ id: "3", url: "https://www.instagram.com/p/DNyXi24Xoo0/" },
{ id: "4", url: "https://www.instagram.com/p/DJmwx8whvlt/" },
{ id: "5", url: "https://www.instagram.com/p/DJmwWWLh7YM/" },
{ id: "6", url: "https://www.instagram.com/p/DJjgdU9vTJJ/" },
{ id: "7", url: "https://www.instagram.com/p/DIOj6JiPXIL/" },
{ id: "8", url: "https://www.instagram.com/p/DFw4oOqvm4z/" },
{ id: "9", url: "https://www.instagram.com/p/DDoLOxkvAvc/" },
{ id: "10", url: "https://www.instagram.com/p/DAdWVDvP9Er/" },
{ id: "11", url: "https://www.instagram.com/p/C_yJHZFNAtu/" },
{ id: "12", url: "https://www.instagram.com/p/C7N7hwJNhHN/" },
{ id: "13", url: "https://www.instagram.com/p/C7JRr_gRLGS/" },
{ id: "14", url: "https://www.instagram.com/p/C7H2qVgS3U0/" },
{ id: "15", url: "https://www.instagram.com/p/C4K9URixjUZ/" },
{ id: "16", url: "https://www.instagram.com/p/C4AcFMbRSPp/" },
{ id: "17", url: "https://www.instagram.com/p/C1Pv1omPLK5/" },
{ id: "18", url: "https://www.instagram.com/p/C08rcl6Ri6C/" },
{ id: "19", url: "https://www.instagram.com/p/CyI8oakRtLc/" },
{ id: "20", url: "https://www.instagram.com/p/CyDZR6mNEC2/" },
{ id: "21", url: "https://www.instagram.com/p/CxzKKRSR5yS/" },
{ id: "22", url: "https://www.instagram.com/p/CreIIzzypGB/" },
{ id: "23", url: "https://www.instagram.com/p/CrbyFH3yowU/" },
{ id: "24", url: "https://www.instagram.com/p/CosADBBvTSd/" },
{ id: "25", url: "https://www.instagram.com/p/CoeeieQPpGN/" },
{ id: "26", url: "https://www.instagram.com/p/Cl39zPzvy1k/" },
{ id: "27", url: "https://www.instagram.com/p/ClJiBNLvA5y/" },
{ id: "28", url: "https://www.instagram.com/p/CjKpBzMPYPo/" },
{ id: "29", url: "https://www.instagram.com/p/CdZsKIoPUQe/" },
{ id: "30", url: "https://www.instagram.com/p/CZJuMP0PSVG/" },
{ id: "31", url: "https://www.instagram.com/p/CW7gta4PnYu/" },
{ id: "32", url: "https://www.instagram.com/p/CWnKciuv0eA/" },
{ id: "33", url: "https://www.instagram.com/p/CUk8Srxt2XG/" },
{ id: "34", url: "https://www.instagram.com/p/CIkne8UHOrB/" },
{ id: "35", url: "https://www.instagram.com/p/CJL67jCniJr/" },
{ id: "36", url: "https://www.instagram.com/p/CIsrvmgHGbY/" },
{ id: "37", url: "https://www.instagram.com/p/CIQts2CnUb3/" },
{ id: "38", url: "https://www.instagram.com/p/CH-v2q0nIBP/" },
{ id: "39", url: "https://www.instagram.com/p/CFuV88lnnKw/" },
{ id: "40", url: "https://www.instagram.com/p/CFpRz4Bn0K3/" },
{ id: "41", url: "https://www.instagram.com/p/CBdzkr5HXqg/" },
{ id: "42", url: "https://www.instagram.com/p/B8nZpg2nkOV/" },
  
];
